# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: pull_request

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
        #👇 Adds Chromatic as a step in the workflow
      - run: yarn build-storybook
      - run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --storybook-build-dir=storybook-static
      # - uses: chromaui/action@v1
      #   # Options required for Chromatic's GitHub Action
      #   with:
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
